services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mycatalog_mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MyCatalog@123"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"   # 👈 porta diferente na sua máquina, pra não bater com o KeyboardProject
    volumes:
      - mssql_data:/var/opt/mssql

  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: mycatalog_sqlpad
    restart: always
    environment:
      SQLPAD_ADMIN: admin@admin.com
      SQLPAD_ADMIN_PASSWORD: admin123
      SQLPAD_APP_LOG_LEVEL: warn
      SQLPAD_WEB_LOG_LEVEL: warn
    ports:
      - "8082:3000"   # 👈 também diferente, já que 8081 é do KeyboardProject
    volumes:
      - sqlpad_data:/var/lib/sqlpad
    depends_on:
      - mssql

volumes:
  mssql_data:
  sqlpad_data: